// Every Arabic string the user sees lives here, so the owner can review it in one place.
// Fixed sentences are copied character for character from CLAUDE.md and design/screens/.

// About page and footer (CLAUDE.md, scholarly rule 6).
const disclaimer = "أداة مساعدة بالذكاء الاصطناعي، لا تحكم على الأحاديث ولا تُفتي";

export const ar = {
  siteName: "سَنَد",
  slogan: "لكلِّ حديثٍ إسناد",

  meta: {
    title: "سَنَد — لكلِّ حديثٍ إسناد",
    titleTemplate: "%s — سَنَد",
    description:
      "ابحث عن حديث، فترى أسانيده بنصّها من كتبها في شجرة واحدة: أين تلتقي، وأين تفترق.",
  },

  skipLink: "تخطَّ إلى المحتوى",

  nav: {
    label: "القائمة الرئيسية",
    home: "سَنَد، الرئيسية",
    // Three links only (owner, 6 Oct): search, paste, about.
    explorer: "محلّل الإسناد",
    sources: "الكتب والمصادر",
    about: "عن المشروع",
  },

  search: {
    label: "ابحث بكلمات الحديث أو باسم راوٍ",
    placeholder: "اكتب كلمات من الحديث أو اسم راوٍ",
    hint: "أو رقم الحديث، مثل: البخاري ١",
    button: "ابحث",
    clear: "مسح",
    clearTitle: "مسح النص",
  },

  disclaimer,
  // The same sentence as written in the design's footers and panels, with its full stop.
  disclaimerLine: `${disclaimer}.`,
  // Every source panel (CLAUDE.md, scholarly rule 6).
  sourceNote: "ذِكرُ الحديث في كتابٍ ليس حكمًا عليه. الأحكام تُنقل منسوبةً إلى قائليها.",

  status: {
    ok: "مصدر موثق",
    check: "يحتاج تحققًا",
    none: "لا مصدر بعد",
  },

  demoTag: "بيانات توضيحية",

  footer: {
    aboutLink: "كيف نعمل، ومن أين ننقل",
    sourcesLink: "المصادر وكيف نتحقق",
    startSearch: "ابدأ البحث",
    demoNote: "البيانات في هذا النموذج بيانات توضيحية.",
  },

  // Place and citation labels.
  place: {
    volume: "ج",
    page: "ص",
    number: "رقم",
  },

  // Counted nouns (all masculine): singular, dual nominative / genitive, plural, accusative singular, definite plural.
  nouns: {
    isnad: {
      one: "إسناد",
      dualNom: "إسنادان",
      dualGen: "إسنادين",
      plural: "أسانيد",
      acc: "إسنادًا",
      definite: "الأسانيد",
      definiteOne: "الإسناد",
    },
    compiler: {
      one: "مصنِّف",
      dualNom: "مصنِّفان",
      dualGen: "مصنِّفَين",
      plural: "مصنِّفين",
      acc: "مصنِّفًا",
      definite: "المصنِّفون",
      definiteOne: "المصنِّف",
    },
    narrator: {
      one: "راوٍ",
      dualNom: "راويان",
      dualGen: "راويَين",
      plural: "رواة",
      acc: "راويًا",
      definite: "الرواة",
      definiteOne: "الراوي",
    },
    hadith: {
      one: "حديث",
      dualNom: "حديثان",
      dualGen: "حديثين",
      plural: "أحاديث",
      acc: "حديثًا",
      definite: "الأحاديث",
      definiteOne: "الحديث",
    },
    name: {
      one: "اسم",
      dualNom: "اسمان",
      dualGen: "اسمين",
      plural: "أسماء",
      acc: "اسمًا",
      definite: "الأسماء",
      definiteOne: "الاسم",
    },
  },

  // Number words used with masculine counted nouns (so 3–10 take the feminine form).
  numbers: {
    one: "واحد",
    units: ["", "", "", "ثلاثة", "أربعة", "خمسة", "ستة", "سبعة", "ثمانية", "تسعة", "عشرة"],
    elevenTens: "أحد عشر",
    twelveNom: "اثنا عشر",
    twelveGen: "اثني عشر",
    teen: "عشر",
    // 21–99: unit + «و» + tens. Units 1 and 2 inside a compound number.
    unitOne: "واحد",
    unitTwoNom: "اثنان",
    unitTwoGen: "اثنين",
    tensNom: ["", "", "عشرون", "ثلاثون", "أربعون", "خمسون", "ستون", "سبعون", "ثمانون", "تسعون"],
    tensGen: ["", "", "عشرين", "ثلاثين", "أربعين", "خمسين", "ستين", "سبعين", "ثمانين", "تسعين"],
    and: "و",
    definitePrefix: "ال",
  },

  home: {
    // «من رواية عمر بن الخطاب رضي الله عنه. عند البخاري ومسلم.»
    narratedBy: (who: string, compilers: string) => `من رواية ${who}. عند ${compilers}.`,
    companionsCount: (count: string) => `${count} من الصحابة`,
    // «صحيح البخاري، حديث ١ · ثمانية أسانيد»
    sourceLine: (book: string, number: string, routes: string) => `${book}، حديث ${number} · ${routes}`,
    openTree: "افتح شجرة الأسانيد",
    listTitle: "الأحاديث",
    // Counts come from data/ (owner, 6 Oct: not a fixed number).
    count: (hadiths: string) => `في الموقع ${hadiths}.`,
    results: (hadiths: string) => `النتائج: ${hadiths}.`,
    noResults: (hadiths: string) =>
      `لا نتائج. في الموقع الآن ${hadiths} فقط. يمكنك لصق إسناد أي حديث ليحلّله الموقع.`,
    pasteButton: "الصق إسنادًا",
    and: "و",
  },

  hadith: {
    back: "نتائج البحث",
    eyebrow: "شجرة الأسانيد",
    // «ثمانية أسانيد عند مصنِّفَين.» Counts from data only; the meeting point comes with Session B.
    counts: (routes: string, compilers: string) => `${routes} عند ${compilers}.`,
    // From the engine: the common link carries every isnad, or only some (owner decision, 6 Oct).
    countsMeetAll: (routes: string, compilers: string, name: string) => `${routes} عند ${compilers}، تلتقي كلها عند ${name}.`,
    countsMeetSome: (routes: string, compilers: string, some: string, name: string) =>
      `${routes} عند ${compilers}، يلتقي ${some} منها عند ${name}.`,
    matnFrom: "نص المتن من",
    variantsSummary: "قراءة أخرى في المتن",
    variantSource: "المصدر",
    tabsLabel: "طريقة العرض",
    tabTree: "الشجرة",
    routesHint: "لكلِّ حديثٍ إسناد. اختر إسنادًا لإبرازه في الشجرة وقراءة نصّه.",
    routeTitle: (book: string, number: string) => `${book}، حديث ${number}`,
    panelTitle: (book: string, number: string) => `${book}، حديث رقم ${number}`,
    panelEyebrow: (no: string, total: string) => `الإسناد ${no} من ${total}`,
    close: "إغلاق اللوحة",
    emptyTitle: "اختر من الشجرة",
    emptyText: "اضغط على راوٍ لترى ترجمته، أو على إسناد في القائمة لتقرأ نصّه.",
    treeLabel: "شجرة الأسانيد",
    treeSoon: "تُرسم الشجرة هنا قريبًا. اختر إسنادًا من القائمة لتقرأ نصّه.",
    panelLabel: "لوحة المصدر",
    isnadText: "الإسناد بنصّه من المصدر",
    chainLabel: "رواة الإسناد",
    chainAria: "من النبي ﷺ في الأعلى إلى المصنِّف في الأسفل",
    place: "الموضع",
    grade: "الحكم المنقول",
    noGrade: "لا حكم مذكور.",
    gradeBy: "قاله",
    gradeFrom: "نقلناه من",
    gradeSource: "المصدر",
    statusLabel: "حالة الإسناد",
    // The source block above the tree (owner, 6 Oct). Values come from the route that carries the matn.
    sourceTitle: "المصدر",
    sourceBook: "الكتاب",
    sourceAuthor: "المصنِّف",
    sourceNumber: "رقم الحديث",
    sourcePlace: "الجزء والصفحة",
    openInSource: "افتح في المصدر",
    notMentioned: "غير مذكور",
    // «كيف أتحقق من هذا؟» under the tree.
    verifyTitle: "كيف أتحقق من هذا؟",
    verifySteps: [
      "افتح الكتاب من زر «افتح الموضع في المصدر».",
      "قارن رقم الحديث بما في الكتاب.",
      "قارن أسماء الرواة في الإسناد واحدًا واحدًا.",
    ],
    allSources: "كل المصادر وحالتها",
    openSource: "افتح الموضع في المصدر",
    copy: "انسخ التوثيق",
    copied: "نُسخ التوثيق",
  },

  narrator: {
    // The role word above the name (design kindName).
    role: {
      prophet: "رأس الإسناد",
      companion: "صحابي",
      narrator: "راوٍ",
      compiler: "مصنِّف",
    },
    tabaqa: "الطبقة",
    death: "الوفاة",
    notReported: "لم تُنقل",
    book: "الكتاب",
    taqribHeading: "قال ابن حجر في «تقريب التهذيب»",
    taqribRef: (page: string, entry: string) => `تقريب التهذيب، ص ${page}، رقم ${entry}`,
    noQuote: "لم ننقل نصّ الحكم بعد، ولن نعرض حكمًا بلا مصدر.",
    prophetNote: "إليه ﷺ ترجع الأسانيد كلها.",
    identification: "تعيين الراوي",
    edition: "الطبعة",
    editionNotMentioned: "غير مذكورة",
    sourceDetails: "تفاصيل المصدر",
    entryNo: "رقم الترجمة",
    page: "الصفحة",
    routesThrough: (routes: string) => `يمرّ به ${routes}:`,
    sourceLink: "المصدر",
  },

  parse: {
    title: "الصق إسنادًا",
    intro: "الصق إسنادًا من أي كتاب. يقرؤه الذكاء الاصطناعي في متصفحك، ثم نبحث عن كل حديث ورد فيه هذا الإسناد أو ما يقاربه.",
    label: "نصّ الإسناد",
    hint: "يكفي الإسناد وحده، ولا يضرّ أن يأتي معه المتن.",
    placeholder: "مثل: حدثنا فلان، قال: حدثنا فلان، عن فلان، عن فلان…",
    privacy: "يُحلَّل النص في متصفحك، ولا نحفظه ولا نرسله.",
    analyse: "حلِّل الإسناد",
    sample: "جرّب مثالًا",
    sampleFrom: (label: string) => `المثال من ${label}، بنصّه.`,
    shortcut: "أو اضغط Ctrl و Enter.",
    counter: (n: string, max: string) => `${n} من ${max} حرف`,
    problems: {
      empty: "الصق نصّ الإسناد أولًا.",
      tooLong: (max: string) => `النص أطول من ${max} حرف. الصق الإسناد وحده، أو جزءًا منه.`,
      notIsnad: "لم نجد في النص إسنادًا: لا صيغة أداء ولا أسماء رواة. الصق نصًّا يبدأ بمثل «حدثنا» أو «عن».",
    },
    noticeTitle: "استخراج آلي — راجِع النتائج",
    noticeText: "قد يخلط الاستخراج الآلي بين رواة يتشابهون في الاسم. راجِع كل اسم قبل أن تعتمد عليه.",
    engine: "قرأ النموذجُ الأسماء في متصفحك، ولم يخرج النص منه.",
    engineRules: "قرأت القواعدُ الأسماء في متصفحك (الطريقة البديلة)، ولم يخرج النص منه.",
    fallbackBanner: "تعمل الآن الطريقة البديلة (القواعد)",
    loadingModel: "نجهّز النموذج في متصفحك…",
    loadingModelPct: (pct: string) => `نجهّز النموذج في متصفحك: ${pct}`,
    reading: "قراءة الإسناد",
    reanalyse: "اقرأ الإسناد",
    matchHigh: "تطابق عالٍ",
    matchMid: "تطابق متوسط",
    chosen: "اخترتَه",
    percent: (n: string) => `${n}٪`,
    matchNote: "نسبة التطابق: من ٩٠٪ فأكثر تطابق عالٍ. أقلّ من ذلك يحتاج تحققًا. ومن لم نجد له ترجمة نعلّمه «لا مصدر بعد».",
    prophet: "رسول الله ﷺ",
    chooserTitle: (name: string) => `من «${name}» هنا؟`,
    chooserByStudent: (best: string, student: string) => `الأقرب ${best}، لأن ${student} يروي عنه في أسانيدنا.`,
    chooserByTeacher: (best: string, teacher: string) => `الأقرب ${best}، لأنه يروي عن ${teacher} في أسانيدنا.`,
    chooserAsk: "اختر لتؤكّد.",
    chooserGroup: (name: string) => `الراوي المقصود بـ«${name}»`,
    chainTitle: "السلسلة كما وردت",
    chainAria: "من النبي ﷺ في الأعلى إلى المصنِّف في الأسفل",
    missingCompiler: "المصنِّف، ولم يُذكر في النص",
    chainNote: "بين كل راويين صيغة الأداء كما جاءت في النص المُلصَق.",
    tahwilFound: "في النص «ح» (تحويل): عرضنا من الأسانيد التي فيه الإسنادَ الذي وجدناه في الشجرة.",
    tahwilMain: "في النص «ح» (تحويل): عرضنا الإسناد الأخير كاملًا.",
    meetingPoint: "نقطة الالتقاء",
    foundTitle: (title: string) => `وجدناه في شجرة «${title}»`,
    foundFirst: (total: string, title: string) => `يطابق الإسناد الأول من ${total}: ${title}.`,
    foundNth: (no: string, total: string, title: string) => `يطابق الإسناد ${no} من ${total}: ${title}.`,
    showInTree: "اعرض الإسناد في الشجرة",
    notFoundTitle: "ليس من الأحاديث المراجَعة التي لها شجرة",
    notFoundText: "لا يطابق هذا الإسناد بعينه أيَّ إسنادٍ في الأحاديث التي راجعناها ورسمنا شجرتها. والأحاديث المطابقة في المجموعة فوق. وهذا لا يقول شيئًا عن صحّته.",
    notFoundChoose: "اختر الراوي المقصود في الأسماء التي تحتاج تحققًا، فنبحث من جديد.",
    announce: (names: string, found: string | null) => (found ? `${names}. وجدناه في شجرة «${found}».` : `${names}. لم نجده في شجرة بعد.`),
  },

  about: {
    metaTitle: "المنهج",
    title: "كيف يعمل سَنَد",
    intro: "مبدؤنا: لكلِّ حديثٍ إسناد. نجمع أسانيد الحديث الواحد بنصّها في شجرة واحدة، لترى أين تلتقي وأين تفترق.",
    stepsTitle: "أربع خطوات",
    steps: [
      { title: "ننقل الأسانيد", text: "نأخذ إسناد كل رواية من كتابها بنصّه، مع الطبعة والجزء والصفحة." },
      {
        title: "نقرأ الإسناد بالذكاء الاصطناعي",
        // 6 Oct (owner): the trained model runs in the browser; the rules take over if it cannot load.
        text: "نموذج ذكاء اصطناعي صغير يعمل في متصفحك يقرأ أسماء الرواة وصيغ الأداء في الإسناد الذي تلصقه. فإن تعذّر عمله قرأته القواعد بدلًا عنه، ونقول ذلك. ثم نطابق الأسماء بأسانيد المجموعة، ونعلّم ما يحتاج تحققًا.",
      },
      {
        title: "نرسم الإسناد المشترك",
        text: "الراوي الذي يتكرّر في أكثر من حديث يصير عقدة واحدة، فتظهر نقطة الالتقاء ونقاط الافتراق، وفي أسفل الرسم الأحاديث.",
      },
      {
        title: "ننقل ولا نحكم",
        text: "ننقل كلام الأئمة بنصّه مع الكتاب والصفحة. وإن لم نجد نصًّا قلنا ذلك، ولم نضع حكمًا من عندنا.",
      },
    ],
    readTitle: "قراءة الشجرة",
    key: {
      prophet: "النبي ﷺ، في أعلى الشجرة",
      companion: "صحابي",
      narrator: "راوٍ بعد الصحابة",
      compiler: "مصنِّف، في أسفل الشجرة",
      common: "نقطة الالتقاء: راوٍ تمرّ به أسانيد كثيرة",
      branch: "نقطة افتراق: حيث يتفرّع الإسناد",
    },
    sourcesTitle: "من أين ننقل",
    booksLabel: "كتب الرواية",
    rijalLabel: "أحكام الرواة",
    // The design's death date is sample content (CLAUDE.md rule 9), so it is left out.
    rijalBook: "تقريب التهذيب، لابن حجر العسقلاني",
    rijalNote: "ننقل عبارته كما هي، مع رقم الترجمة والصفحة.",
    editionsLabel: "الطبعات المعتمدة",
    // As al-Maktaba al-Shamila records them (docs/SOURCES.md); no edition is filled in from memory.
    editionsPlaceholder: "صحيح البخاري: ط السلطانية. صحيح مسلم: ت عبد الباقي. تقريب التهذيب: الطبعة غير مذكورة. كما في بيانات المكتبة الشاملة.",
    listJoin: "، و",
    statusTitle: "ثلاث حالات للدليل",
    statusText: {
      ok: "النص منقول من المصدر، وموضعه مراجَع.",
      check: "استُخرج آليًّا، أو لم يُراجَع موضعه بعد. لا تعتمد عليه قبل المراجعة.",
      none: "لم نجد له مصدرًا، أو لم ننقله بعد. وهذا لا يعني أن الحديث موضوع.",
    },
    statusNote: "هذه حالات للدليل، لا أحكام على الحديث. أحكام الأئمة نصوص ننقلها منسوبةً إلى قائليها، ولا نلوّنها.",
    limitsTitle: "ما لا يُحسنه الاستخراج الآلي",
    limits: [
      "قد يخلط بين رواة يتشابهون في الاسم، مثل «سفيان» بين ابن عيينة والثوري.",
      "قد يخطئ في قراءة النص غير المشكول، أو في تقطيع الأسماء.",
      "لا يرجّح بين أقوال الأئمة، ولا يحكم على حديث بصحة أو ضعف.",
      "المطابقة بالاسم كما ورد، وقد يشترك راويان في الاسم نفسه.",
      "الأحاديث التي نجدها من مجموعة خارجية لم تُراجَع على كتبها، وترخيصها غير واضح. الأحاديث المراجَعة وحدها لها شجرة محققة.",
      "الشجرة تعرض ما وجدناه من أسانيد فقط، وقد يكون للحديث أسانيد أخرى.",
      "ارجع دائمًا إلى المصدر المطبوع، واسأل أهل العلم.",
    ],
    privacyTitle: "الخصوصية",
    privacyText: "لا حسابات ولا تتبّع. ما تلصقه في «محلّل الإسناد» يُحلَّل في متصفحك، ولا يُحفظ ولا يُرسل إلينا.",
  },

  notFound: {
    metaTitle: "الصفحة غير موجودة",
    title: "لم نجد هذه الصفحة",
    text: "قد يكون الرابط ناقصًا أو قديمًا. ابدأ من الصفحة الرئيسية.",
  },

  tree: {
    zoomIn: "تكبير",
    zoomOut: "تصغير",
    reset: "إعادة الشجرة إلى وضعها",
    resetShort: "إعادة الضبط",
    // One line under the legend (owner, 6 Oct).
    legendNote: "نقطة الالتقاء: راوٍ تلتقي عنده أكثر الأسانيد. نقطة الافتراق: موضع يتفرّع منه الإسناد إلى أكثر من راوٍ.",
    hintMobile: "اسحب لتحريك الشجرة، واضغط على راوٍ لتظهر ترجمته.",
    hintDesktop: "النبي ﷺ في الأعلى، والمصنِّفون في الأسفل. اسحب للتحريك.",
    zoomPct: (pct: string) => `${pct}٪`,
    nodeAria: (name: string, role: string) => `${name}، ${role}`,
  },

  // The narrator panel on the hadith page (design «لوحة الراوي»). Counts come from the engine.
  narratorPanel: {
    label: "لوحة الراوي",
    roleCommon: (role: string) => `${role}، وهو نقطة الالتقاء`,
    prophetNote: "إليه ﷺ ترجع الأسانيد كلها في هذه الشجرة.",
    commonAll: (definite: string) => `تمرّ به ${definite} كلها`,
    commonSome: (count: string, total: string) => `تمرّ به ${count} من ${total}`,
    branchesTo: (students: string) => `، ومنه تتفرّع إلى ${students}`,
    through: (count: string, total: string) => `يمرّ به ${count} من ${total}`,
    throughMarked: "، وهي مُعلَّمة في القائمة.",
    showRoutes: "اعرض الأسانيد",
    fullPage: "الترجمة كاملة",
    thruSelected: "يمرّ بالراوي المختار",
  },

  legend: {
    prophet: "النبي ﷺ",
    companion: "صحابي",
    narrator: "راوٍ",
    compiler: "مصنِّف",
    common: "نقطة الالتقاء",
    branch: "نقطة افتراق",
    selected: "المختار",
  },

  // The explorer: hadiths found for a pasted isnad (owner, 6 Oct). Counts come from the matching, never typed.
  explorer: {
    hero: "الصق إسنادًا من أي كتاب. يقرؤه الذكاء الاصطناعي، ثم نبحث عن كل حديث ورد فيه هذا الإسناد أو ما يقاربه.",
    rule: "ننقل ولا نحكم. لا نؤلّف حديثًا ولا راويًا ولا إسنادًا: كل نتيجة حديث موجود في المجموعة.",
    loadingCorpus: "نحمّل مجموعة الأحاديث…",
    loadError: "تعذّر تحميل المجموعة. أعد المحاولة.",
    title: "الأحاديث التي ورد فيها هذا الإسناد",
    summary: (total: string, same: string, contains: string, close: string) =>
      `وجدنا ${total}: ${same} بالإسناد نفسه، و${contains} بإسناد يحتويه، و${close} بإسناد قريب.`,
    none: "لم نجد في المجموعة حديثًا بهذا الإسناد. وهذا لا يعني أنه غير موجود في الكتب.",
    tooShort: "الإسناد قصير، فقد تظهر أحاديث كثيرة. أضف رواة لتضيّق النتائج.",
    classes: { same: "الإسناد نفسه", contains: "إسناد يحتويه", close: "إسناد قريب" },
    classHelp: {
      same: "كل رواتك فيه بالترتيب نفسه، ولا زيادة.",
      contains: "كل رواتك فيه بالترتيب نفسه، وفيه رواة زيادة.",
      close: "بعض رواتك فيه بالترتيب نفسه، وبعضهم غير موجود.",
    },
    score: (matched: string, total: string) => `${matched} من ${total} رواة`,
    extras: (n: string) => `رواة زيادة: ${n}`,
    missing: (n: string) => `رواة غير موجودين: ${n}`,
    asWritten: "المطابقة بالاسم كما ورد؛ وقد يشترك راويان في الاسم نفسه.",
    graphTitle: "الإسناد المشترك في رسم واحد",
    graphNote: (drawn: string, total: string) => `رسمنا أفضل ${drawn} من ${total}. والقائمة تحته فيها الكل.`,
    graphHint: "اضغط حديثًا لتبرز سلسلته، أو راويًا لترى أحاديثه.",
    graphAllNote: "الراوي أو الحديث المختار يظهر في القائمة تحت الرسم.",
    listTitle: "كل الأحاديث المطابقة",
    filterBook: "الكتاب",
    filterClass: "نوع التطابق",
    all: "الكل",
    narrow: "ضيِّق النتائج بأسماء من الإسناد",
    narrowPlaceholder: "اكتب اسم راوٍ",
    selectedNode: (name: string) => `الأحاديث التي يمرّ بها «${name}»`,
    clearSelection: "إلغاء الاختيار",
    shown: (shown: string, total: string) => `يظهر ${shown} من ${total}`,
    more: "أظهر المزيد",
    noFilterResult: "لا حديث يوافق هذا التضييق.",
    status: "يحتاج تحققًا — من مجموعة خارجية لم تُراجَع",
    open: "افتح الحديث",
    bookNumber: (book: string, n: string) => `${book}، حديث ${n}`,
    isnadAsInCorpus: "الإسناد كما في المجموعة",
    prophetNode: "النبي ﷺ",
    hadithRole: "حديث",
    narratorRole: "راوٍ",
    aiTitle: "ما يفعله الذكاء الاصطناعي وما لا يفعله",
    aiDoes: "يقرأ الأسماء وصيغ الأداء في الإسناد الذي تلصقه، وفي إسناد كل حديث في المجموعة.",
    aiDoesnt: "لا يؤلّف حديثًا ولا راويًا ولا مصدرًا. المطابقة والترتيب حسابٌ ثابت على نصوص المجموعة، ونتيجته نفسها في كل مرة.",
  },

  // /c/<book>/<n>: one hadith of the external corpus, with the evidence for it.
  corpusHadith: {
    metaTitle: "حديث من المجموعة",
    loading: "نحمّل الحديث…",
    notFound: "لم نجد هذا الحديث في المجموعة.",
    back: "ارجع إلى المحلّل",
    fullText: "نص الحديث كما في المجموعة",
    fullTextMissing: "لا نص كامل لهذا الرقم في المجموعة. هذا إسناده كما وردت.",
    fullTextLoading: "نحمّل النص الكامل…",
    fullTextFailed: "تعذّر تحميل النص الكامل. هذا إسناده كما وردت، والمصدر في الرابط تحته.",
    isnadOnly: "الإسناد كما في المجموعة",
    readTitle: "أسماء الرواة كما قرأها النموذج",
    readNote: "قراءة آلية للإسناد، تحتمل الخطأ. قارنها بالنص.",
    readNone: "لم يجد النموذج أسماء في هذا النص.",
    readLoading: "نحمّل أسماء الرواة…",
    sourceTitle: "المصدر",
    book: "الكتاب",
    number: "الرقم في المجموعة",
    corpus: "المجموعة",
    corpusName: "fawazahmed0/hadith-api",
    pinned: "النسخة المثبّتة",
    openFile: "افتح ملف المصدر",
    status: "يحتاج تحققًا — من مجموعة خارجية لم تُراجَع",
    statusText: "نقلنا الحديث كما هو من مجموعة خارجية، ولم يراجعه صاحب المشروع على كتابه. الترخيص غير واضح.",
    verifyTitle: "كيف أتحقق من هذا؟",
    verifySteps: [
      "افتح الكتاب المطبوع أو في المكتبة الشاملة، واذهب إلى هذا الحديث.",
      "قارن الرقم؛ فترقيم المجموعة قد يختلف عن الطبعة.",
      "قارن أسماء الرواة في الإسناد واحدًا واحدًا.",
    ],
    allSources: "كل المصادر وحالتها",
  },

  // /sources (owner, 6 Oct): every book and site Sanad copies from, and what has been checked. Counts come from data/.
  sources: {
    metaTitle: "المصادر",
    title: "المصادر وكيف نتحقق",
    intro: "كل نصّ في الموقع منقول من هذه الكتب، ومعه رابط صفحته. وهنا ما راجعناه منها وما لم نراجعه بعد.",
    textTitle: "كتب ننقل منها النص",
    notesTitle: "كتب نستشهد بها في الملاحظات",
    notesText: "نذكرها لتعيين راوٍ أو لتوضيح قراءة، برابط الصفحة. لا نعرض نصّها في الموقع.",
    author: "المؤلف",
    edition: "الطبعة كما في الشاملة",
    use: "ماذا ننقل منه",
    open: "افتح المصدر",
    noLink: "لا رابط محفوظ",
    isnads: (total: string, checked: string) => `الأسانيد المنقولة منه: ${total}. راجعها صاحب المشروع: ${checked}.`,
    entries: (total: string, checked: string) => `التراجم المنقولة منه: ${total}. راجعها صاحب المشروع: ${checked}.`,
    quotes: (total: string, checked: string) => `النصوص المنقولة منه: ${total}، في أسانيد راجعها صاحب المشروع: ${checked}.`,
    licenceNote: "رخصة الموقع غير واضحة، فننقل منه الحكم القصير مع قائله ورابطه فقط.",
    corpusTitle: "مجموعة الأحاديث التي نبحث فيها",
    corpusIntro: "هذه الأحاديث لا نكتبها نحن. نجلبها كما هي من مجموعة خارجية مفتوحة، ونقرأ إسناد كل حديث بالنموذج لنقارنه بالإسناد الذي تلصقه.",
    corpusName: "المجموعة",
    corpusRepo: "المستودع",
    corpusPin: "النسخة المثبّتة",
    corpusCount: (total: string) => `عدد الأحاديث: ${total}`,
    corpusStatus: "كلها يحتاج تحققًا: لم نراجعها على كتبها.",
    corpusLicence: "ترخيص النصوص غير واضح: المجموعة لا تذكر مصدرها، وترخيص برمجتها فقط حرّ.",
    corpusNumbering: "ترقيمها قد يختلف عن ترقيم الطبعات، وخاصة في صحيح مسلم.",
    corpusNoGrades: "لا ننقل منها أحكامًا ولا ترجمة.",
    corpusFile: "ملف الكتاب",
    booksIn: "الكتب فيها",
    modelTitle: "النموذج الذي يقرأ الإسناد",
    modelText: "نموذج ذكاء اصطناعي صغير (BERT-mini عربي) درّبناه على Sanadset ليستخرج أسماء الرواة. يعمل في متصفحك، ولا يخرج منه النص.",
    modelBase: "النموذج الأساس",
    modelData: "بيانات التدريب",
    modelMeasured: "الدقة المقيسة: F1 ‏٠٫٩١٦ على ٣٠٠ إسناد من كتب لم يرها في التدريب، مقابل ٠٫٧٥٧ للقواعد.",
    modelLicence: "ترخيص بيانات التدريب غير واضح. ننشر النموذج بقرار من صاحب المشروع، ونذكر ذلك هنا.",
    modelFallback: "إن تعذّر تحميله قرأت القواعد الإسناد بدلًا عنه، وتقول الصفحة ذلك.",
    verifiedTitle: "الأحاديث التي راجعناها",
    verifiedText: (hadiths: string, isnads: string) => `${hadiths}، وفيها ${isnads} راجعها صاحب المشروع على كتبها. هذه وحدها لها شجرة محققة.`,
  },

  placeholder: {
    intro: "ابحث عن حديث، فترى أسانيده بنصّها من كتبها في شجرة واحدة: أين تلتقي، وأين تفترق.",
    building: "الموقع قيد البناء.",
  },
} as const;
